controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

# Route pour la page d'accueil
home:
  path: /search
  controller: App\Controller\VehiculeController::index
